FROM node:23-bookworm-slim AS builder

COPY . /app
WORKDIR /app

ENV time_zone=Asia/Seoul
ENV NODE_ENV=production

RUN corepack enable
RUN corepack prepare pnpm --activate
RUN pnpm install --frozen-lockfile

ENV NEXT_PUBLIC_API_URL=https://api.tapie.kr
ENV API_HOSTNAME=https://api.tapie.kr
ENV API_VERSION=v1
ENV AUTH_URL=https://auth.tapie.kr

FROM builder AS production

WORKDIR /app/packages/under-construction

RUN pnpm build

ENV PORT=3002
EXPOSE 3002

CMD ["pnpm", "start"]